language: python

python:
  - "2.7"

before_install:
  - sudo apt-get install -y build-essential gdal-bin libgdal-dev libproj-dev

install:
  - pip install --user requirements.txt
  - pip install --user requirements-dev.txt

addons:
  apt:
    update: true

script:
  - make test
